-- 섯다 웹 (독립 모듈 seotda/) — 최초 1회 실행
-- 기존 tb_* 테이블·코드와 분리. 홀짝/지갑과 공유하는 것: tb_member.point, tb_point_log(지급로그)

CREATE TABLE IF NOT EXISTS `tb_seotda_room` (
  `idx` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_token` VARCHAR(12) NOT NULL,
  `host_nick` VARCHAR(32) NOT NULL,
  `guest_nick` VARCHAR(32) DEFAULT NULL COMMENT 'NULL 또는 SYSTEM=솔로, 실닉=매칭',
  `mode` ENUM('solo','match_pending','waiting','pvp') NOT NULL DEFAULT 'solo',
  `bet_amount` BIGINT UNSIGNED NOT NULL DEFAULT 100000000,
  `host_ready` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `guest_ready` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `solo_phase` ENUM('idle','playing','done') NOT NULL DEFAULT 'idle',
  `pvp_phase` ENUM('idle','playing','done') NOT NULL DEFAULT 'idle',
  `round_no` INT UNSIGNED NOT NULL DEFAULT 0,
  `pot` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `host_card1` TINYINT UNSIGNED DEFAULT NULL,
  `host_card2` TINYINT UNSIGNED DEFAULT NULL,
  `host_card3` TINYINT UNSIGNED DEFAULT NULL COMMENT '3장 중 2장 선택',
  `guest_card1` TINYINT UNSIGNED DEFAULT NULL,
  `guest_card2` TINYINT UNSIGNED DEFAULT NULL,
  `guest_card3` TINYINT UNSIGNED DEFAULT NULL,
  `sys_card1` TINYINT UNSIGNED DEFAULT NULL COMMENT '솔로: 시스템 패',
  `sys_card2` TINYINT UNSIGNED DEFAULT NULL,
  `sys_card3` TINYINT UNSIGNED DEFAULT NULL,
  `host_picked` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `guest_picked` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `host_pick1` TINYINT UNSIGNED DEFAULT NULL COMMENT '선택 슬롯 1-3',
  `host_pick2` TINYINT UNSIGNED DEFAULT NULL,
  `guest_pick1` TINYINT UNSIGNED DEFAULT NULL,
  `guest_pick2` TINYINT UNSIGNED DEFAULT NULL,
  `host_peek_slot` TINYINT UNSIGNED DEFAULT NULL COMMENT '호스트 랜덤 공개 슬롯 1-3',
  `guest_peek_slot` TINYINT UNSIGNED DEFAULT NULL COMMENT '게스트 랜덤 공개 슬롯 1-3',
  `waiting_since` DATETIME DEFAULT NULL,
  `guest_action_since` DATETIME DEFAULT NULL COMMENT '게스트 선택 대기 시작',
  `ready_wait_since` DATETIME DEFAULT NULL COMMENT '한쪽 준비 후 상대 응답 대기',
  `last_result` VARCHAR(255) DEFAULT NULL,
  `online_at` DATETIME DEFAULT NULL COMMENT '섯다 페이지 status heartbeat',
  `host_emote` VARCHAR(16) DEFAULT NULL COMMENT '호스트 최근 리액션',
  `host_emote_at` DATETIME DEFAULT NULL COMMENT '호스트 리액션 시각',
  `guest_emote` VARCHAR(16) DEFAULT NULL COMMENT '게스트 최근 리액션 키',
  `guest_emote_at` DATETIME DEFAULT NULL COMMENT '게스트 리액션 시각',
  `pending_bet_amount` BIGINT UNSIGNED DEFAULT NULL COMMENT '배팅 변경 요청액',
  `pending_bet_by` VARCHAR(32) DEFAULT NULL COMMENT '배팅 변경 요청자',
  `pending_bet_at` DATETIME DEFAULT NULL COMMENT '배팅 변경 요청 시각',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idx`),
  UNIQUE KEY `uk_room_token` (`room_token`),
  KEY `idx_host` (`host_nick`),
  KEY `idx_guest` (`guest_nick`),
  KEY `idx_mode_waiting` (`mode`, `waiting_since`),
  KEY `idx_online_at` (`online_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tb_seotda_queue` (
  `nick` VARCHAR(32) NOT NULL,
  `bet_amount` BIGINT UNSIGNED NOT NULL DEFAULT 100000000,
  `queued_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`nick`),
  KEY `idx_queued_at` (`queued_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tb_seotda_log` (
  `idx` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `room_token` VARCHAR(12) NOT NULL DEFAULT '',
  `mode` VARCHAR(16) NOT NULL DEFAULT '',
  `host_nick` VARCHAR(32) NOT NULL DEFAULT '',
  `guest_nick` VARCHAR(32) NOT NULL DEFAULT '',
  `bet_amount` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `winner_nick` VARCHAR(32) DEFAULT NULL,
  `host_label` VARCHAR(32) DEFAULT NULL,
  `guest_label` VARCHAR(32) DEFAULT NULL,
  `host_delta` BIGINT NOT NULL DEFAULT 0,
  `guest_delta` BIGINT NOT NULL DEFAULT 0,
  `regdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idx`),
  KEY `idx_room` (`room_id`),
  KEY `idx_host_reg` (`host_nick`, `regdate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
