-- 경매 낙찰 주문
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `tb_auction_order` (
    `ao_idx`           INT UNSIGNED     NOT NULL AUTO_INCREMENT            COMMENT '주문 고유번호',
    `au_idx`           INT UNSIGNED     NOT NULL                           COMMENT '경매글 번호',
    `mb_idx`           INT UNSIGNED     NOT NULL                           COMMENT '낙찰자(구매자)',
    `seller_mb_idx`    INT UNSIGNED     NOT NULL                           COMMENT '판매자',
    `addr_idx`         INT UNSIGNED         NULL DEFAULT NULL              COMMENT '선택 배송지 번호',
    `ao_addr_label`    VARCHAR(30)      NOT NULL DEFAULT ''                COMMENT '배송지명 스냅샷',
    `ao_addr_name`     VARCHAR(50)      NOT NULL                           COMMENT '받는 분',
    `ao_addr_phone`    VARCHAR(20)      NOT NULL                           COMMENT '연락처',
    `ao_addr_zip`      VARCHAR(10)      NOT NULL                           COMMENT '우편번호',
    `ao_addr_road`     VARCHAR(255)     NOT NULL                           COMMENT '도로명주소',
    `ao_addr_jibun`    VARCHAR(255)         NULL DEFAULT NULL              COMMENT '지번주소',
    `ao_addr_extra`    VARCHAR(100)     NOT NULL DEFAULT ''                COMMENT '참고항목',
    `ao_addr_detail`   VARCHAR(100)     NOT NULL DEFAULT ''                COMMENT '상세주소',
    `ao_addr_message`  VARCHAR(200)     NOT NULL DEFAULT ''                COMMENT '배송 메시지',
    `ao_courier_name`  VARCHAR(50)      NOT NULL DEFAULT ''                COMMENT '택배사명',
    `ao_tracking_no`   VARCHAR(50)      NOT NULL DEFAULT ''                COMMENT '운송장번호',
    `ao_shipped_at`    DATETIME             NULL DEFAULT NULL              COMMENT '운송장 등록일시',
    `ao_buyer_confirmed_at` DATETIME      NULL DEFAULT NULL              COMMENT '구매자 구매확정 일시',
    `ao_seller_settle_amount` INT UNSIGNED NOT NULL DEFAULT 0              COMMENT '판매자 정산액(원)',
    `ao_platform_fee`  INT UNSIGNED     NOT NULL DEFAULT 0                 COMMENT '플랫폼 수수료(원)',
    `ao_refunded_at`   DATETIME             NULL DEFAULT NULL              COMMENT '환불 완료 일시',
    `ao_refund_amount` INT UNSIGNED     NOT NULL DEFAULT 0                 COMMENT '환불 금액(원)',
    `ao_refund_requested_at` DATETIME      NULL DEFAULT NULL              COMMENT '환불 신청 일시',
    `ao_amount`        INT UNSIGNED     NOT NULL DEFAULT 0                 COMMENT '결제 금액(원)',
    `ao_pay_method`    VARCHAR(20)      NOT NULL DEFAULT 'cash'            COMMENT 'cash|card',
    `ao_card_last4`    VARCHAR(4)           NULL DEFAULT NULL              COMMENT '카드 테스트: 끝 4자리',
    `ao_pay_status`    TINYINT UNSIGNED NOT NULL DEFAULT 0                 COMMENT '0:미결제 1:결제완료',
    `ao_order_status`  TINYINT UNSIGNED NOT NULL DEFAULT 1                 COMMENT '1:주문접수 2:배송준비 3:배송중 4:배송완료 5:구매확정 6:환불완료 9:취소',
    `ao_created_at`    DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '주문일시',
    `ao_paid_at`       DATETIME             NULL DEFAULT NULL              COMMENT '결제일시',
    `ao_updated_at`    DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (`ao_idx`),
    UNIQUE KEY `uq_ao_au_idx` (`au_idx`),
    KEY `idx_ao_mb_idx` (`mb_idx`, `ao_pay_status`),
    KEY `idx_ao_seller` (`seller_mb_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='경매 낙찰 주문';
